### PR TITLE
⬆️ Webpack 5

### PR DESCRIPTION
**Pull request by Maykin-99**
(Still work in progress)

One issue so far is the dependency `iconv-lite` of `steam-categories`. The version used in `steam-categories` is not compatible with the latest Webpack when using `"electron-renderer"` as a target. [The issue is documented in their repository](https://github.com/ashtuchkin/iconv-lite/issues/205) but it has been fixed in the latest version.
My current solution is to use Yarn instead of Npm, since it lets us override the version of any dependency (I've tried other solutions but none were working for me).

If a switch is not desired then `steam-categories` needs to be updated.

### CODE REVIEW

**Comment by cbartondock** [comment]
I think the clean option here is to update steam-categories. I know the code there pretty well I can look into it. What version of iconv-lite does it need to get to?

**Comment by Maykin-99** [comment]
The latest is `0.6.3`, so I'd go with that. The API hasn't changed as far as I can see.

**Comment by Maykin-99** [comment]
The pull request isn't finished yet. It was still a draft.

**Comment by cbartondock** [comment]
So I am seeing unresolved peer dependencies on npm install; for example
` peer webpack@"^3.1.0" from extract-text-webpack-plugin@3.0.2`

**Comment by cbartondock** [comment]
Sorry yeah I was just testing it out on my end (I merged to another branch not master). I will re-open it.

**Comment by cbartondock** [comment]
Hmm I reverted but it actually doesn't look liek  can re-open the PR. Sorry about that. Submit another when you're ready.

**Pull request merged**
