### PR TITLE
Amazon games parser

### PR DESCRIPTION
**Pull request by lexarvn**
Noticed there wasn't a parser for Amazon Games. It has a few changes beyond just adding a parser though.
To support launching games directly, ended up needing to add yaml to parse amazon's out of spec fuel.json.
Also to support launching games directly, needed to allow individual games to have launch options defined as well as start in a different directory than the executable, not just when starting a game via a launcher.

### CODE REVIEW

**Comment by cbartondock** [comment]
Code looks great, but I am having trouble understanding why the parser needs a "start in directory" input? Why not just make it start in the correct directory (rather than exposing that potentially confusing setting to the user)? Similarly for launch options, seems like that could be added in the parsers's code rather than letting the user set them (if they are always the same)

**Comment by lexarvn** [comment]
Sorry, I'm not sure what you mean. As far as I'm aware, I did not expose inputs for "start in directory" or "launch options" to the user, but maybe I just missed where they are exposed? Looks like my branch is out of date though so maybe I need to update it and it will become apparent.

As is though, this is what is displayed to the user as parser inputs and I don't see them:
image

**Comment by cbartondock** [comment]
Oh I see I take it back! It was just the ParsedData model that changed. No issue with that. If you wouldn't mind doing the merge to bring your work up to speed on your end that would be great, if not I can create a test branch and merge into that.

**Comment by lexarvn** [comment]
Yup, I can merge in the changes in

**Comment by lexarvn** [comment]
Ok, got it all up to date

**Comment by cbartondock** [comment]
Okay great thank you! I will merge it into a test branch, run some tests, and then merge into master. 

Thanks for the PR!

**Comment by cbartondock** [comment]
@lexarvn if you are interested please join the [SteamGridDB discord](https://discord.gg/kfNqd7rgkt) and dm me over there and I will add you to the SRM developer chat (for discussing PRs etc).

**Comment by lexarvn** [comment]
@cbartondock sure, I joined it, but what is your username over there? Can't exactly dm you without that and I don't see a user of a similar name as your github one over there

**Comment by cbartondock** [comment]
@lontanadascienza

**Pull request merged**
