### PR TITLE
Merge and rename presets

### PR DESCRIPTION
**Pull request by kencinder**

### CODE REVIEW

**Comment by cbartondock** [comment]
I can merge this but it won't affect the 2.3.0 presets (I have split up the files already). You may have to do those separately :/

**Comment by kencinder** [comment]
I could just rebase against master now I guess

**Comment by cbartondock** [comment]
Okay thank you! Let me know when it's done and I will merge

**Comment by cbartondock** [comment]
Actually wait you did them per file actually I should be able to merge this now.

**Pull request merged**
