### PR TITLE
Add SteamScraper image provider

### PR DESCRIPTION
**Pull request by KP2048**
see https://repo.withertech.com/scraper/api/

### CODE REVIEW

**Comment by cbartondock** [comment]
This is awesome! Mind if I merge it into a temporary branch to test and then merge to master?

**Comment by KP2048** [comment]
sure

**Comment by KP2048** [comment]
it might time out for new roms. all the images are cached on the server so if someone requests a rom that hasen't been scraped before it might take a little bit to scape and generate the images. any subsequent requests of files with the same md5 will be just as instantaneous as SteamGridDB

**Comment by KP2048** [comment]
if it times out wait a little bit for it to finish running on the server, then try again and it should work. i could probably change the timeout setting to be longer to compensate

**Comment by cbartondock** [comment]
Okay I'll let you know what I see!

**Comment by doZennn** [comment]
Name is a little misleading, no? I can see people confusing it with something that scrapes Steam. Maybe some mention of ScreenScraper.fr should be put somewhere?

**Comment by KP2048** [comment]
all the image authors are Screenscraper.fr

**Comment by KP2048** [comment]
the api documentation also states that it retrieves images from screenscraper and generates images using those images for use in srm.

**Comment by cbartondock** [comment]
I will add that info to the in app SRM documentation for the provider also.

**Pull request merged**
