### PR TITLE
Reduce retrogaming.cloud API calls

### PR DESCRIPTION
**Pull request by AlexDobeck**
I think this might (help) resolve what I was describing in: https://github.com/FrogTheFrog/steam-rom-manager/issues/46.

I didn't go through the fuzzyMatcher in detail, but it seemed to be very likely to accept all the results retrogaming.cloud provided. 

Many games return 15 results (without messing with the pagination stuff), meaning we had at least 16 calls made per game, and with the 60rpm limit, we were down to about 3-4 games per minute. For medium to large libraries this was exceptionally painful.

The changes are:

1. For every exact title match found it will load all images -- 2 Api calls most of the time
2. If there is not an exact match, it will use the Fuzzy Matcher and only use the 'most_popular_media_url' provided by the API -- 1 Api call always

If the game has many title matches (for instance Earthbound returns 3 matches for the different platforms) you'd get 1 + (number of matches) api calls, however this is somewhat rare.

The little testing I've done have been much nicer, only taking a minute and a half to load my library of 70 games, as opposed to the 30+ minutes prior.

### CODE REVIEW

**Review by FrogTheFrog — CHANGES_REQUESTED** [review]
`retrograming.cloud` has way too many similar titles, thus `listData[i].name === this.proxy.title` will most likely always evaluate to false. This will result in getting top images only.

You should evaluate the title with `fuzzyMatcher` like in the issue you opened (#46):
```
if (listData[i].id !== undefined && listData[i].name && this.proxy.fuzzyMatcher.fuzzyEqual(this.proxy.title, listData[i].name, true, true)) promises.push(this.retrieveMediaData(listData[i].id));
```
 and then after `promises.push(...)` you can also check for top image url and add it if it exists (like you did in the next for loop).

**Comment by AlexDobeck** [comment]
Maybe I'm using it wrong, but if I alter the code to:


```
for (let i = 0; i < listData.length; i++) {
                    if (this.proxy.filter && !this.proxy.fuzzyMatcher.fuzzyEqual(this.proxy.title, listData[i].name, true, true))
                        continue;
                    if (listData[i].id !== undefined && listData[i].name !== undefined && listData[i].most_popular_media_url !== '')
                        promises.push(this.retrieveMediaData(listData[i].id));
                }
```

I see almost all evaluation of fuzzyEqual returning 'true' resulting in the 16 or so api requests per game as it was before.

The current pr was definitely assuming that a 'strong-parser' which correctly identifies titles gets priority. I could see how that is definitely not the goal, but maybe fuzzyEqual is too lenient at the moment?

**Comment by AlexDobeck** [comment]
There does seem to be something up with fuzzyMatcher.fuzzyEqual... I'm getting these logs:
```
Fuzzy compare: "Bubsy II" == "Bubsy II"
Fuzzy compare: "Bubsy II" == "Bubsy in Claws Encounters of the Furred Kind"
Fuzzy compare: "Bubsy II" == "Bubsy 3D - Furbitten Planet"
Fuzzy compare: "Bubsy II" == "Bubsy II"
Fuzzy compare: "Bubsy II" == "Bubsy in Claws Encounters of the Furred Kind"
Fuzzy compare: "Bubsy II" == "Bubsy II"
Fuzzy compare: "Bubsy II" == "Pokemon - Generation III - Version RubisPokemon - Generation III - Version Rubis"
Fuzzy compare: "Bubsy II" == "Shining Force III - Scenario III"
Fuzzy compare: "Bubsy II" == "Back to the Future Part II & III"
Fuzzy compare: "Bubsy II" == "Castlevania III - Dracula's Curse"
Fuzzy compare: "Bubsy II" == "Dragon Warrior III"
Fuzzy compare: "Bubsy II" == "Ikari Warriors III - The Rescue"
Fuzzy compare: "Bubsy II" == "Ninja Gaiden III - The Ancient Ship of Doom"
Fuzzy compare: "Bubsy II" == "Teenage Mutant Ninja Turtles III - The Manhattan Project"
Fuzzy compare: "Bubsy II" == "Wizards & Warriors III - Kuros...Visions of Power"
```

**Comment by FrogTheFrog** [comment]
@AlexDobeck You have master (2.1.0) branch active. It needs to be changed to 2.2.0 branch.

**Edit:** Honestly, I have no idea, why `fuzzyEqual` doesn't work. It seems that you're using 2.2.0 branch, but for some reason it has a bug that is in master branch.

**Comment by FrogTheFrog** [comment]
I have made those changes myself as I am about to publish another pre-release. Will give credit to you for finding and fixing this bug.

**Pull request closed without merging**
