### PR TITLE
Controller manager patches

### PR DESCRIPTION
**Pull request by Godsbane**
[fix const controllerNames](https://github.com/SteamGridDB/steam-rom-manager/commit/b4e4614bbcde129886cb0a96efa764c9e198a64a)

 
[Controller Manager:](https://github.com/SteamGridDB/steam-rom-manager/commit/c0bfbcae6dc00789c9eda163c8bf7a3a4f2608a3) 

Updates title to only equal localization.english
 if the title is set to #title

 
[Controller Manager:](https://github.com/SteamGridDB/steam-rom-manager/commit/ed0a3c79c220a5cb9c33336b152589bb37e1180b) 

Alphabetizes the returned list of controllers

### CODE REVIEW

**Comment by Godsbane** [comment]
ok i think is ready.

Now properly finds all templates, uses the Title, applies right type (workshop or template) and applies the filename as the mapping for templates.

tested on linux

image

**Comment by cbartondock** [comment]
Looks great, the only thing I am not sure about is the "#Title" logic. Why not just always use the localization title? It seems to always be unique (so long as the files are actually distinct).

Edit:

Actually sorry I realize I made a bunch of changes to controller manager last night in order to add an "Unset controllers" button in the parser. The merge is going to be tricky so I am going to merge this into a different branch and then I will make the merge.

**Comment by Godsbane** [comment]
The reasoning for me is simply that we've been using the title field without localization (in emudeck). While yes i can (and will) clean them up for the future, previous installs will be potentially affected.

Without following the same logic as the steam client, it will make certain things wonky for others who used the same method; outside emudeck if they didn't setup localization either.

**Comment by cbartondock** [comment]
All SRM uses that title for is what to display in the list the user selects from, so I don't think it's a big deal which we use so long as they are unique. For that reason I decided to go with just the localization title - there is no reason to make it more complicated than it needs to be, and it should facilitate us switching over to the user's local language in SRM in future. 

Other than that everything is great, merged into master.

**Pull request merged**
