### PR TITLE
Using `com.epicgames.launcher://` as `executableLocation` inside Epic parser

### PR DESCRIPTION
**Pull request by Marocco2**
Doing this I could remove Windows Powershell v1.0 dependency over Epic parser

### CODE REVIEW

**Comment by cbartondock** [comment]
Did you have access to epic online services when doing it this way?

**Comment by Marocco2** [comment]
> Did you have access to epic online services when doing it this way?

Indeed, it will launch Epic launcher

**Comment by cbartondock** [comment]
Okay sick. I do basically this for gog I just couldn't figure out what the correct name was for the epic launcher.

**Comment by cbartondock** [comment]
Sorry I had to revert this as the typing is actually broken, such that `npm run build:dist` errors out. You need to update the model for `ParsedData` appropriately (preferably without breaking other parsers by adding an optional executableLocation field under `ParsedData.success`). I believe you will also need to make changes to `src\lib\file-parser` to ensure that this field is actually used. Please test and re-submit the PR.

If you're not sure how to do this I can make the changes for you and credit you in the release.

**Comment by Marocco2** [comment]
> Sorry I had to revert this as the typing is actually broken, such that `npm run build:dist` errors out. You need to update the model for `ParsedData` appropriately (preferably without breaking other parsers by adding an optional executableLocation field under `ParsedData.success`). I believe you will also need to make changes to `src\lib\file-parser` to ensure that this field is actually used. Please test and re-submit the PR.
> 
> If you're not sure how to do this I can make the changes for you and credit you in the release.

You may be much faster than I am rn to make changes and testing, so go ahead 👍

**Pull request merged**
