### PR TITLE
➖ remove Bluebird

### PR DESCRIPTION
**Pull request by Maykin-99**
Some notes:

- I removed the `concurrency` part. I think we've been using it wrong anyway, since the `concurrency` value only applies to the promises created by the `mapper` and not those passed as `input`. Those are being executed directly. See documentation: http://bluebirdjs.com/docs/api/promise.map.html
- I had to implement an alternative to Bluebird's `Promise.cancel` but I'm not really sure how to trigger that. I doubt it is even used.

### CODE REVIEW

**Comment by cbartondock** [comment]
I would have guessed that it is used when you are downloading a bunch of images and you cancel half way through (the user has that option). Specifically the stopUrlDownload function of the image provider service gets called and I believe some "onCancel" handling is used. Can you verify that with your changes all of that still works? The images should instantly stop populating if the user hits stop downloading images.

**Comment by Maykin-99** [comment]
Bluebird's `cancel` method is only used once, namely in `xRequest.cancel`: 

https://github.com/doZennn/steam-rom-manager/blob/6c077980750dacbe99bb82bc6a542903d12a44fa/src/lib/x-request.ts#L44-L49

Which is only called in `SteamGridDbProvider.stopUrlDownload`:

https://github.com/doZennn/steam-rom-manager/blob/6c077980750dacbe99bb82bc6a542903d12a44fa/src/lib/image-providers/steamgriddb.worker.ts#L61-L63

But the `onCancel` of that promise does nothing:

https://github.com/doZennn/steam-rom-manager/blob/6c077980750dacbe99bb82bc6a542903d12a44fa/src/lib/image-providers/steamgriddb.worker.ts#L55-L57

I don't think that the `onCancel` in `xRequest.makeRequest` is ever used:

https://github.com/doZennn/steam-rom-manager/blob/6c077980750dacbe99bb82bc6a542903d12a44fa/src/lib/x-request.ts#L141-L143

> The images should instantly stop populating if the user hits stop downloading images.

The "Stop image providers"-Button is only briefly there for 1 second and even if hit on time, the pictures are still being loaded.
The `xRequest.cancel` method is being called though but as I said, `onCancel` does nothing in this case.

That also happens in `master`, as far as I can tell.

**Comment by cbartondock** [comment]
Okay you're right it does nothing "on cancel" but nevertheless the cancellation functionality is still being used. Believe me in master if you have a lot of images (say 400 games = 1600 images) it won't take a second to download and if you hit the stop button it will stop populating. I just need to verify that that still happens, ie that your replacement for the promise.cancel functionality works.

**Comment by cbartondock** [comment]
Thanks again for your contributions by the way. SRM could use some tlc that I haven't had the bandwidth to give it.

**Comment by cbartondock** [comment]
I don't see how your cancel handling is actually cancelling the promises? I see that it is calling an "oncancel" that does nothing just like before (your cancel handler weakmap), but is it actually cancelling the promises - stopping them from executing?

**Comment by cbartondock** [comment]
I also agree that that use of concurrency is incorrect, but it would be nice if we could change it so that SRM actually does avoid hammering SGDB with a bazillion requests at once. I'll look into it when I get home.

**Comment by cbartondock** [comment]
Having tested out your code your promise cancellation actually is working, and which is more you seem to have fixed an error with SGDB where it was giving an error for logos. So I am going to merge this into master. We can think about adding in concurrency via something like [this](https://dev.to/kepta/comment/3o1e).

**Comment by Maykin-99** [comment]
> SRM could use some **tlc** [...]

I don't know what it means but you're welcome. My primary objective is actually to build a CLI for SRM, but I figured there are things that needs to be done before I feel comfortable working on this project. Let's see when I have time for that.





> I don't see how your cancel handling is actually cancelling the promises? I see that it is calling an "oncancel" that does nothing just like before (your cancel handler weakmap), but is it actually cancelling the promises - stopping them from executing?

The WeakMap tracks each Promise created in `makeRequest` and its `cancel` method that will eventually call `xhr.abort()`.
You can't stop a Promise from executing. As soon as it is instantiated it will run. What we're doing here is cancelling the XHR request which will settle the promise.

> [...] and which is more you seem to have fixed an error with SGDB where it was giving an error for logos.

I noticed but that was due to the `package-lock.json` that was pointing to an old commit of `steamgriddb` that hasn't implemented the `getLogos` method yet. So I can't take credit for that.


> We can think about adding in concurrency via something like [this](https://dev.to/kepta/comment/3o1e).

We should use this: https://www.npmjs.com/package/p-map

**Comment by cbartondock** [comment]
A command line interface would be fantastic. Some other major features I know people would like are:
* Google Drive Sync of profiles and images so that SRM can work on multiple machines
* More Parsers (origin for example)
* Ability to change which title the game matches with from sgdb after the fact.
* Management of controller profiles in steam, so that a parser could specify which profile to use. 

So there is plenty to work on if you have time and are interested!

**Pull request merged**
