### PR TITLE
⬆️ Webpack 5

### PR DESCRIPTION
**Pull request by Maykin-99**

### CODE REVIEW

**Comment by cbartondock** [comment]
The Zone.js issue has not been fixed actually. If I do `rm -rf node_modules; rm package-lock.json; npm i; npm run build:dist; npm run start` I get the same error

**Comment by Maykin-99** [comment]
Yeah, I'm confused.

Could you try removing this line:

https://github.com/doZennn/steam-rom-manager/blob/a263870295698fb2d4987029d9445282a4693b86/src/lib/zone-bluebird.ts#L10

Either way, I'd probably replace `bluebird` with native Promises in a separate PR if you don't mind.

**Comment by cbartondock** [comment]
Feel free to submit that PR - I haven't touched the promise API. I'm sure the original dev had a good reason for using bluebird in 2017 but probably no longer necessary as you say. I believe Bluebird is mostly used explicitly in src/lib/x-request.ts, but possibly in a few other places.

**Comment by cbartondock** [comment]
Okay deleting that line fixed the issue and doesn't seem to have broken anything. I'm still somewhat hesitant about it since it seems to be in all the bluebird docs from that era, in terms of how to make bluebird compatible with zone. I'm worried that we may introduce subtle bugs arising from promises settling in the wrong zones.

**Comment by cbartondock** [comment]
Wow interestingly I was reading [here](https://github.com/angular/zone.js/issues/455) and there is a comment from the original developer of SRM with this exact issue.

**Comment by cbartondock** [comment]
Okay I merged the changes without commenting out the Zone.js line, so package-lock.json is still necessary for now. I'll wait for your PR and barring that do more research into zone aware promises.

**Pull request merged**
