### PR TITLE
rpcs3 Profile update - Separate PS3 and PSN custom variable

### LINKED ISSUE #606: [Request] PS3 - Custom Variable should separate Disc & PSN games
This could be an easy fix to [that issue](https://github.com/SteamGridDB/steam-rom-manager/issues/561).

SRM creates shortcuts for games and their updates which is bothersome, separating it should solve it as Extracted ISOs should be in "rpcs3\games" and PSN games in "rpcs3\dev_hdd0\game"

Variable : 
PS3 : Disc based -->BLUS/BLES/BLAS/BCUS/etc..
PSN : NPEB/NPUB/etc..

I'll gladly do the PR.

### PR DESCRIPTION
**Pull request by Immersion95**
-Separate PS3 and PSN in the custom variable
-Rename the profiles accordingly

SRM creates shortcuts for games and their updates which is bothersome, separating it should solve it as Extracted ISOs should be in "rpcs3\games" and PSN games in "rpcs3\dev_hdd0\game"

Closes https://github.com/SteamGridDB/steam-rom-manager/issues/606 & https://github.com/SteamGridDB/steam-rom-manager/issues/561

### CODE REVIEW

**Comment by kencinder** [comment]
I have some questions and perhaps issues with this PR

1: I'm not well versed in PS3 Title IDs. I assume where the added `PSN` was put in CustomVariables, that BL** games(And the few KTGS and others) are disc based games, whereas NP** are PSN based games?

2: If that's the case, the changes to the PS3 preset file appear insufficient and incorrect.

You've changed the title to Extracted ISO (Removing the PSN part) but are using the `PSN` custom variable.
If the extracted ISO files correspond to disc games they should still be using the `PS3` custom variable should they not?

The Installed PKG preset for RPCS3 would then use the `PSN` custom variable?

**Comment by kencinder** [comment]
I misread something and deleted my comment...

I don't know PS3 Title IDs or RPCS3 very well, assuming the differences where the `PSN` IDs start is 100% purely a Disc VS PSN thing and Installed PKG is PSN only?
Is it possible to run ISOs directly as well?
Does the Extracted ISO preset need to even remain named as such or will it handle both extracted and unextracted games? If so we can drop the `Extracted ISO` part entirely.

Before I approve this I just want to know all the bases are covered.

**Comment by Immersion95** [comment]
> I misread something and deleted my comment...
> 
> I don't know PS3 Title IDs or RPCS3 very well, assuming the differences where the `PSN` IDs start is 100% purely a Disc VS PSN thing and Installed PKG is PSN only? Is it possible to run ISOs directly as well? Does the Extracted ISO preset need to even remain named as such or will it handle both extracted and unextracted games? If so we can drop the `Extracted ISO` part entirely.
> 
> Before I approve this I just want to know all the bases are covered.

Yes ISO and PSN titles always start differently, PSN titles always start with N. No disc start with N.

We still need extracted ISO preset and I also renamed it to make it clearer.

ISO extracted files should always remain in a different folder rpcs3\games and the structure is not the same.

The installed PKGs all go in the same folder whether it's PSN or updates, this was causing issues as SRM picks the updates as another game.

PS3 needs 2 presets, 1 for extracted ISO and 1 for installed PKGs.

PS : We use extracted ISO because rpcs3 doesn't handle ISO file at all. It's a requested feature and the team should implement it in the future.

**Comment by kencinder** [comment]
Alright since no plain ISO support, left as is and merged

**Pull request merged**
