### PR TITLE
initial UWP parser, gamepass compatible

### PR DESCRIPTION
**Pull request by perroboc**
Scans a directory for UWP games, and extracts the launching parameters from Windows.Management.Deployment.PackageManager using powershell. Tested against gamepass games.

### CODE REVIEW

**Comment by cbartondock** [comment]
Sorry, why was this closed?

**Comment by alvaromunoz** [comment]
["Hey there, thanks for the pr!
We already have official steam asset support for boop planned for a future site update that will manage it in a cleaner manner."](https://discord.com/channels/488621078302949377/533198732163022858/1009209818529144923)

**Comment by perroboc** [comment]
No activity for 3 months.

**Comment by cbartondock** [comment]
Yes I wasn't active at the time, however I would have eventually merged it! I just merged a few PRs that were opened nearly a year ago. Please re-open it and I will deal with the merge conflicts. Assuming it was working?

**Comment by perroboc** [comment]
I can't open it, the fork was deleted. I'll upload an updated merge

**Pull request closed without merging**
