### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by ghost**
It's a complete translation, I didn't reread it there are probably mistakes

### CODE REVIEW

**Comment by FrogTheFrog** [comment]
I will wait till final 2.2.0 release and then merge. There will be some outdated text, that I will need you to address.

@ThePiranhaPlant I will try to keep memo of what has changed. Could you post version for which you did translation?

**Comment by ghost** [comment]
@FrogTheFrog I don't really know I just made a git clone of the master branch a couple of weeks ago. I removed the downloaded code I guess it was version 2.2-7.

**Comment by FrogTheFrog** [comment]
@ThePiranhaPlant If it was 2.2.0-7, could you check [this](https://github.com/FrogTheFrog/steam-rom-manager/compare/ce8d482...master#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) and fix the differences? Language files start somewhere at the bottom. 

Also for about page, could you insert this just below contributors?

```
## Translators

* `ThePiranhaPlant` - French translation.
```

Or something similar (in french of course).

**Comment by FrogTheFrog** [comment]
User became ghost 👻

**Pull request closed without merging**
