### PR TITLE
Add "Wii U" Category for TitleIDs to customVariables.json.

### PR DESCRIPTION
**Pull request by ZombiJambi**
Cemu added the ability to install base games to the mlc01 directory, mimicking the real Wii. These use title IDs to identify, so I've added Titles for each. Some may need to be modified to match the name on SteamGridDB.com more closely. Example: "Disney Epic Mickey 2: The Power of Two" is the proper title, but returns the wrong game in SGdb.com, so I renamed it to simply: "Disney Epic Mickey 2" to get the correct result.

### CODE REVIEW

**Comment by kencinder** [comment]
Would recommend having the correct titles as per the manufacturer, eg cover art/title screen etc...rather than adjusting names to match what isn't correct on steamgriddb.

Names can and should be corrected on steamgriddb to match the above.

**Comment by doZennn** [comment]
Or even better, you can query games on SGDB via the titleid. Which I've painstakingly assigned to the correct game on SGDB already.

**Comment by kencinder** [comment]
> Or even better, you can query games on SGDB via the titleid. Which I've painstakingly assigned to the correct game on SGDB already.

Wouldn't that require support in SRM itself? This file is nothing more than a list really.

If there are incorrect names based on those TitleID's though, on SGDB, they should be corrected.

**Comment by cbartondock** [comment]
@doZennn That's a good idea and could be added. Is it just Wii U that you have queryable titles for or do you also have PS3 and MAME? Not sure what others need it.

**Comment by cbartondock** [comment]
Closing as subsumed by @klepp0906's PR (all CEMU variables). Will still look into using steamgriddb's titleid API

**Pull request closed without merging**
