### PR TITLE
⬆️ Webpack 5

### PR DESCRIPTION
**Pull request by Maykin-99**

### CODE REVIEW

**Comment by cbartondock** [comment]
So I updated steam categories to use a newer iconv-lite by the way! Lmk when you think this is ready.

**Comment by Maykin-99** [comment]
I think it's ready.
The changes have been tested on Linux with Node 14.18.1.

Compilation also works on Node 15.14.0, 16.13.0 and 17.0.1, but haven't tested how it behaves there.

Quick summary what I did:

- updated Webpack to 5
- removed babel
- replaced old loaders with new ones
- replaced `node-sass` with `sass`
- migrated Webpack configuration to TypeScript
- some adjustments to the source code itself:
  - in `.scss` files there were some `/deep/`statements. It is not supported by `sass` and it has been deprecated in Chrome. I replaced it with `::ng-deep` but I don't know if it works
  - division with `/` in Sass is deprecated. Replaced with `math.div`
  - `worker-loader` is not necessary anymore. We can just call `new Worker(new URL(...))` and Webpack knows what to do.
  - `child.constructor.name === 'SomeConstantString'` does not work in production because of minification, so I introduced a static `displayName` property

**Comment by cbartondock** [comment]
Awesome work. Testing it now.

**Comment by cbartondock** [comment]
So compilation works but the app does not load - I can't even open dev tools.

**Comment by cbartondock** [comment]
Did it work on your end? I just did `npm i; npm run build:dist; npm run start`

**Comment by Maykin-99** [comment]
Yes, it works on my end. Maybe try `npm ci` instead of `npm i`? Which Node & npm version are you using?

The DevTools in production doesn't open because of this: https://github.com/doZennn/steam-rom-manager/blob/7211fd9485b7f518f656f639dc62b8d59d61614c/src/main/app.ts#L43
Not sure why it worked before, but it wasn't supposed to, I think.

**Comment by cbartondock** [comment]
Node 14.18.1, npm 8.1.1. Hmm well I'll fix that then because it's useful for debugging to have it work even in production.

**Comment by Maykin-99** [comment]
> Node 14.18.1, npm 8.1.1.

I'm using npm 8.1.2 but that shouldn't make any difference. 

With 👇️

```sh
ELECTRON_ENABLE_LOGGING=1 npm start
```

we can also see the logs in the terminal

**Comment by cbartondock** [comment]
After enabling logging I see:
`"Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)", source: file:///D:/Projects/Development/steam-rom-manager/dist/renderer/renderer.bundle.js (2)`

With the same result as before, the app opens but is stuck on the spinning wheel.

I should probably mention that I am building on Windows. I'll test on Linux once it's working here.

**Comment by cbartondock** [comment]
Okay so the issue was that I had somehow deleted the package-lock.json file that you had. When I did git stash and ran everything again I no longer saw that error and SRM opened up. So just installing from package.json doesn't work because of the above error. Would be nice if we could fix that but it's not a big deal. The ::ng-deep tag worked, I know what styling it's supposed to apply and it does it.

**Comment by Maykin-99** [comment]
> So just installing from package.json doesn't work because of the above error. 

Can confirm. After upgrading `zone.js` I get the same issue.

The only library that comes to my mind that would override `Promise` is `bluebird`

I'll look into it.

**Comment by cbartondock** [comment]
Another issue at the moment is that npm run validate-files is not working right now, which is preventing continuous integration from passing:

```
D:\Projects\Development\steam-rom-manager\.validate-files.ts:1
import { configPresets } from "./src/renderer/schemas/config-presets.schema";

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module.m._compile (D:\Projects\Development\steam-rom-manager\node_modules\ts-node\src\index.ts:400:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Projects\Development\steam-rom-manager\node_modules\ts-node\src\index.ts:403:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at Object.<anonymous> (D:\Projects\Development\steam-rom-manager\node_modules\ts-node\src\bin.ts:141:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

**Comment by cbartondock** [comment]
Okay I fixed the validate-files issue by updating ts-node to the latest version and adding an override to tsconfig.js so that ts-node uses module "CommonJS" instead of "ESNext." The build is now passing!

**Comment by Maykin-99** [comment]
I think both issues have been resolved now.

`bluebird` provides a `noConflict()` function that let's you return the original Promise.

**Comment by cbartondock** [comment]
Great! Do you want to submit an additional PR to the webpack5 branch with your changes?

**Pull request merged**
